runtime: python
env: flex
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app

runtime_config:
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cpu_utilization:
    target_utilization: 0.6
