"""Add new relationships to User model

Revision ID: 9de75df24a6c
Revises: b0395490462e
Create Date: 2026-01-22 11:06:56.558960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de75df24a6c'
down_revision = 'b0395490462e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
