"""Add audience column to posts table

Revision ID: b0395490462e
Revises: 4a016eb94c9d
Create Date: 2026-01-21 08:34:29.048047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0395490462e'
down_revision = '4a016eb94c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
