
"""indexes views

Revision ID: 07_indexes_views
Revises: 06_studies_core
Create Date: 2023-10-27 10:06:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07_indexes_views'
down_revision = '06_studies_core'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_comments_created_at', 'comments', ['created_at'], unique=False)

    op.execute("""
    CREATE MATERIALIZED VIEW user_engagement_view AS
    SELECT
        u.id AS user_id,
        u.full_name,
        COUNT(p.id) AS posts_count,
        COUNT(c.id) AS comments_count,
        COUNT(f.follower_id) AS following_count,
        (SELECT COUNT(*) FROM followers WHERE followed_id = u.id) AS followers_count
    FROM users u
    LEFT JOIN posts p ON u.id = p.owner_id
    LEFT JOIN comments c ON u.id = c.owner_id
    LEFT JOIN followers f ON u.id = f.follower_id
    GROUP BY u.id, u.full_name;
    """)

    op.execute("""
    CREATE MATERIALIZED VIEW post_engagement_view AS
    SELECT
        p.id AS post_id,
        p.text,
        u.full_name AS author,
        COUNT(c.id) AS comments_count,
        (SELECT COUNT(*) FROM post_likes WHERE post_id = p.id) AS likes_count
    FROM posts p
    JOIN users u ON p.owner_id = u.id
    LEFT JOIN comments c ON p.id = c.post_id
    GROUP BY p.id, u.full_name;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP MATERIALIZED VIEW post_engagement_view")
    op.execute("DROP MATERIALIZED VIEW user_engagement_view")
    op.drop_index('ix_comments_created_at', table_name='comments')
    op.drop_index('ix_messages_created_at', table_name='messages')
    # ### end Alembic commands ###
